package utils

var RuleChinese = map[string]string{
	"Disallowed SSH Connection":                                             "禁止ssh连接",
	"Unexpected outbound connection destination":                            "意外的出站连接目的地",
	"Unexpected inbound connection source":                                  "意外的入站连接源",
	"Modify Shell Configuration File":                                       "修改shell配置文件",
	"Read Shell Configuration File":                                         "读取shell配置文件",
	"Schedule Cron Jobs":                                                    "调度定时任务",
	"Update Package Repository":                                             "更新包存储库",
	"Write below binary dir":                                                "在二进制目录下写入",
	"Write below monitored dir":                                             "在被监控的目录下写入",
	"Read ssh information":                                                  "读取ssh信息",
	"Write below etc":                                                       "在etc目录写入",
	"Write below root":                                                      "在/或者/root写入",
	"Read sensitive file trusted after startup":                             "启动后读取受信任的敏感文件",
	"Read sensitive file untrusted":                                         "读取未受信任的敏感文件",
	"Write below rpm database":                                              "在rmp数据库写入",
	"DB program spawned process":                                            "DB程序产生新进程",
	"Modify binary dirs":                                                    "更改二进制目录",
	"Mkdir binary dirs":                                                     "创建二进制目录",
	"Change thread namespace":                                               "更改线程命名空间",
	"Run shell untrusted":                                                   "运行未受信任的shell",
	"Launch Privileged Container":                                           "启动特权容器",
	"Launch Sensitive Mount Container":                                      "启动有敏感挂载的容器",
	"Launch Disallowed Container":                                           "启动不允许的容器",
	"System user interactive":                                               "系统用户交互",
	"Terminal shell in container":                                           "容器内的终端shell",
	"System procs network activity":                                         "系统处理网络活动",
	"Program run with disallowed http proxy env":                            "使用不允许的http代理环境运行程序",
	"Interpreted procs inbound network activity":                            "入站程序的网络活动",
	"Interpreted procs outbound network activity":                           "出站程序的网络活动",
	"Contact EC2 Instance Metadata Service From Container":                  "从容器连接EC2实例元数据服务",
	"Contact K8S API Server From Container":                                 "从容器连接k8s api-server",
	"Unexpected K8s NodePort Connection":                                    "意外的节点端口连接",
	"Launch Package Management Process in Container":                        "容器中启动包管理进程",
	"Netcat Remote Code Execution in Container":                             "容器中的Netcat远程执行代码",
	"Launch Suspicious Network Tool in Container":                           "在容器中启动可疑网络工具",
	"Launch Suspicious Network Tool on Host":                                "在宿主机上启动可以的网络额工具",
	"Search Private Keys or Passwords":                                      "搜索私钥或者密码",
	"Clear Log Activities":                                                  "清理日志的活动",
	"Remove Bulk Data from Disk":                                            "从磁盘中删除批量数据",
	"Delete or rename shell history":                                        "删除或者重命名shell历史",
	"Delete Bash History":                                                   "删除bash历史",
	"Set Setuid or Setgid bit":                                              "设置用户或者用户组",
	"Create Hidden Files or Directories":                                    "创建隐藏目录或者文件",
	"Launch Remote File Copy Tools in Container":                            "在容器内启动远程文件复制工具",
	"Create Symlink Over Sensitive Files":                                   "在敏感文件上创建符号链接",
	"Detect outbound connections to common miner pool ports":                "检测到普通矿池端口的出站连接",
	"Detect crypto miners using the Stratum protocol":                       "使用Stratum协议检测加密矿工",
	"The docker client is executed in a container":                          "Docker客户端在容器中执行",
	"Packet socket created in container":                                    "在容器中创建的数据包套接字",
	"Network Connection outside Local Subnet":                               "本地子网外部的网络连接",
	"Outbound or Inbound Traffic not to Authorized Server Process and Port": "出站或入站流量不流向授权服务器的进程和端口",
	"Redirect STDOUT/STDIN to Network Connection in Container":              "将STDOUT / STDIN重定向到容器中的网络连接",
	"Container Drift Detected (chmod)":                                      "在容器中检测到漂移",
	"Container Drift Detected (open+create)":                                "检测到容器漂移（打开+创建）",
	"Outbound Connection to C2 Servers":                                     "与C2服务器的出站连接",
	"Linux Kernel Module Injection Detected":                                "检测到Linux内核模块注入",
	"Container Run as Root User":                                            "容器以根用户身份运行",
	"Sudo Potential Privilege Escalation":                                   "Sudo潜在特权升级",
	"Debugfs Launched in Privileged Container":                              "在特权容器中启动Debugfs",
	"Mount Launched in Privileged Container":                                "在特权容器中启动挂载",

	"Disallowed K8s User":                                     "不允许的K8s用户",
	"Create Disallowed Pod":                                   "创建不允许的pod",
	"Create Privileged Pod":                                   "创建特权容器",
	"Create Sensitive Mount Pod":                              "创建有敏感挂载的pod",
	"Create HostNetwork Pod":                                  "创建hostnetwork类型pod",
	"Create NodePort Service":                                 "创建NodePort类型的service",
	"Create/Modify Configmap With Private Credentials":        "使用专用证书创建/修改Configmap",
	"Anonymous Request Allowed":                               "匿名请求被允许",
	"Attach/Exec Pod":                                         "附加/执行pod的命令",
	"EphemeralContainers Created":                             "临时容器创建",
	"Create Disallowed Namespace":                             "创建不允许的namespace",
	"Pod Created in Kube Namespace":                           "在kube-system或者kube-public下创建pod",
	"Service Account Created in Kube Namespace":               "在kube-system或者kube-public下创建serviceAccount",
	"System ClusterRole Modified/Deleted":                     "系统ClusterRole在修改或者删除",
	"Attach to cluster-admin Role":                            "附加到集群管理员角色",
	"ClusterRole With Wildcard Created":                       "含有通配符的集群角色创建",
	"ClusterRole With Write Privileges Created":               "含有特权的集群角色的创建",
	"ClusterRole With Pod Exec Created":                       "含有pod exec的集群角色的创建",
	"K8s Deployment Created":                                  "deployment创建",
	"K8s Deployment Deleted":                                  "deployment删除",
	"K8s Service Created":                                     "service创建",
	"K8s Service Deleted":                                     "service删除",
	"K8s ConfigMap Created":                                   "configmap创建",
	"K8s ConfigMap Deleted":                                   "configmap删除",
	"K8s Namespace Created":                                   "namespace创建",
	"K8s Namespace Deleted":                                   "namespace删除",
	"K8s Serviceaccount Created":                              "serviceAccount创建",
	"K8s Serviceaccount Deleted":                              "serviceAccount删除",
	"K8s Role/Clusterrole Created":                            "role/clusterRole的创建",
	"K8s Role/Clusterrole Deleted":                            "role/clusterRole的删除",
	"K8s Role/Clusterrolebinding Created":                     "role/clusterrolebinding的创建",
	"K8s Role/Clusterrolebinding Deleted":                     "role/clusterrolebinding的删除",
	"K8s Secret Created":                                      "secret创建",
	"K8s Secret Deleted":                                      "secret删除",
	"All K8s Audit Events":                                    "所有的k8s审计事件",
	"Full K8s Administrative Access":                          "完整的K8s管理访问权限",
	"Ingress Object without TLS Certificate Created":          "ingress对象没有配置tls证书",
	"Untrusted Node Successfully Joined the Cluster":          "不受信任节点成功加入集群",
	"Untrusted Node Unsuccessfully Tried to Join the Cluster": "不受信任节点未成功尝试加入集群",
}

var RuleDescChinese = map[string]string{
	"Disallowed SSH Connection":                                             "检测所有的 ssh 连接，如果主机不在目标主机的允许连接列表",
	"Unexpected outbound connection destination":                            "检测允许的 ips、网络或域名之外与目的地的任何出站连接",
	"Unexpected inbound connection source":                                  "从允许的 ips、网络或域名之外的源检测任何入站连接",
	"Modify Shell Configuration File":                                       "检测会修改shell配置文件的尝试",
	"Read Shell Configuration File":                                         "检测会读取shell配置文件的尝试",
	"Schedule Cron Jobs":                                                    "检测已经调度的定时任务",
	"Update Package Repository":                                             "检测软件包存储库获取更新",
	"Write below binary dir":                                                "试图写入一组二进制目录下的任何文件",
	"Write below monitored dir":                                             "试图写入一组被监控目录下的任何文件",
	"Read ssh information":                                                  "非ssh程序尝试读取ssh目录下的任何文件",
	"Write below etc":                                                       "尝试在etc目录下写入任何文件",
	"Write below root":                                                      "尝试在/,/root目录写入任何文件",
	"Read sensitive file trusted after startup":                             "试图读取任何敏感文件（例如，包含用户/密码/身份验证的文件，启动后由受信任的程序提供。受信任的程序可能会读取这些文件。在启动时加载初始状态，但不是之后。",
	"Read sensitive file untrusted":                                         "试图读取任何敏感文件（例如，包含用户/密码/身份验证的文件信息）。已知的受信任程序例外。",
	"Write below rpm database":                                              "非rmp相关程序在rpm的数据库写入",
	"DB program spawned process":                                            "与数据库服务器相关的程序产生了一个新进程，而不是它本身。这不应该发生，是一些SQL注入攻击的后续行为。",
	"Modify binary dirs":                                                    "尝试修改一组二进制目录下的文件",
	"Mkdir binary dirs":                                                     "尝试在一组二进制目录下创建目录",
	"Change thread namespace":                                               "尝试更改程序/线程的命名空间（通常完成作为创建容器的一部分）调用setns。",
	"Run shell untrusted":                                                   "尝试在非shell应用程序下生成shell。监控特定应用程序。",
	"Launch Privileged Container":                                           "检测在特权容器中启动的初始进程。对于已知的受信任映除外。",
	"Launch Sensitive Mount Container":                                      "检测由从敏感主机目录装载的容器启动的初始进程（即/proc）。对于已知的受信任映像除外。",
	"Launch Disallowed Container":                                           "检测不在允许容器列表中的容器启动的初始进程。",
	"System user interactive":                                               "系统（即非登录）用户试图运行交互式命令的行为。",
	"Terminal shell in container":                                           "一个shell被用作一个带有附加终端的容器的入口点/执行点。",
	"System procs network activity":                                         "系统二进制文件执行的，预期不会发送或接收任何网络流量的任何网络活动",
	"Program run with disallowed http proxy env":                            "尝试运行带有不允许的HTTP_PROXY环境变量的程序",
	"Interpreted procs inbound network activity":                            "任何解释程序（perl，python，ruby等）执行的任何入站网络活动",
	"Interpreted procs outbound network activity":                           "任何解释程序（perl，python，ruby等）执行的任何出站网络活动",
	"Unexpected UDP Traffic":                                                "UDP通信不在端口53（DNS）或其他常用端口上",
	"Non sudo setuid":                                                       "尝试通过调用setuid来更改用户。 sudo / su除外。用户“ root”和“ nobody”,由于setuid调用通常涉及丢弃特权，因此也排除了针对自身的请求。",
	"User mgmt binaries":                                                    "可以管理用户，密码或权限的任何程序的活动，sudo和su除外。一些基于linux发行版本的容器在启动的时候创建自定义用户也被排除-一些容器在顶部创建自定义用户。排除了一些实际上不会更改任何内容的无害命令行。",
	"Create files below dev":                                                "在/dev下创建除管理设备的已知程序以外的任何文件。一些rootkits将文件隐藏在/dev中。",
	"Contact EC2 Instance Metadata Service From Container":                  "检测从容器连接EC2实例元数据服务的尝试",
	"Contact K8S API Server From Container":                                 "检测从容器联系K8S API服务器的尝试",
	"Unexpected K8s NodePort Connection":                                    "从容器中检测使用K8s NodePorts的尝试",
	"Launch Package Management Process in Container":                        "包管理进程在容器中运行",
	"Netcat Remote Code Execution in Container":                             "Netcat程序在允许远程执行代码的容器中运行",
	"Launch Suspicious Network Tool in Container":                           "检测容器内启动的网络工具",
	"Launch Suspicious Network Tool on Host":                                "检测宿主机上启动的网络工具",
	"Search Private Keys or Passwords":                                      "检测grep私钥或密码活动。",
	"Clear Log Activities":                                                  "检测清除关键日志文件",
	"Remove Bulk Data from Disk":                                            "检测正在运行的进程以清除磁盘中的批量数据",
	"Delete or rename shell history":                                        "检测shell历史记录删除",
	"Delete Bash History":                                                   "检查bash历史删除",
	"Set Setuid or Setgid bit":                                              "设置用户或者用户组",
	"Create Hidden Files or Directories":                                    "检查创建隐藏目录或者文件",
	"Launch Remote File Copy Tools in Container":                            "检测容器内远程文件复制工具的启动",
	"Create Symlink Over Sensitive Files":                                   "检测通过敏感文件创建的符号链接",
	"Detect outbound connections to common miner pool ports":                "矿工通常连接到公共端口上的矿池。",
	"Detect crypto miners using the Stratum protocol":                       "矿工通常会指定要以“ stratum + tcp”开头的URI连接到的矿池",
	"The docker client is executed in a container":                          "检测在容器内执行的k8s客户端工具",
	"Packet socket created in container":                                    "在容器中的设备驱动程序（OSI第2层）级别上检测新的数据包套接字。数据包套接字可被攻击者用于ARP欺骗和特权升级（CVE-2020-14386）。",
	"Network Connection outside Local Subnet":                               "检测流量以在本地子网外部进行映像。",
	"Outbound or Inbound Traffic not to Authorized Server Process and Port": "检测不属于授权服务器进程和端口的流量。",
	"Redirect STDOUT/STDIN to Network Connection in Container":              "在容器（潜在的反向外壳）中检测将标准输出/标准输入重定向到网络连接。",
	"Container Drift Detected (chmod)":                                      "chmod在容器中创建了新的可执行文件",
	"Container Drift Detected (open+create)":                                "由于open+create在容器中创建了新的可执行文件",
	"Outbound Connection to C2 Servers":                                     "检测到命令和控制服务器的出站连接",
	"Linux Kernel Module Injection Detected":                                "检测内核模块被注入（从容器中）。",
	"Container Run as Root User":                                            "检测到以root用户身份运行的容器",
	"Sudo Potential Privilege Escalation":                                   "特权升级漏洞，影响sudo（<= 1.9.5p2）。使用sudoedit -s或sudoedit -i命令（带有命令行参数）来执行sudo，该命令行参数以来自非特权用户的单个反斜杠字符结尾，可以将用户特权提升为root用户。",
	"Debugfs Launched in Privileged Container":                              "检测在特权容器内启动的文件系统调试器debugfs，这可能导致容器转义。",
	"Mount Launched in Privileged Container":                                "检测文件系统安装是否发生在特权容器内，这可能导致容器逃逸。",

	"Disallowed K8s User":                                     "在允许的用户集中检测用户的任何k8s操作。",
	"Create Disallowed Pod":                                   "检测到尝试使用允许的图像列表之外的容器图像启动容器的尝试。",
	"Create Privileged Pod":                                   "检测尝试启动的pod带有特权容器",
	"Create Sensitive Mount Pod":                              "从敏感的主机目录（即/ proc）中检测尝试使用卷启动pod的尝试。已知的受信任镜像会发生例外。",
	"Create HostNetwork Pod":                                  "检测使用宿主机网络启动的pod",
	"Create NodePort Service":                                 "检测创建的服务是NodePort类型的",
	"Create/Modify Configmap With Private Credentials":        "检测创建/修改包含私有证书（aws密钥，密码等）的配置映射",
	"Anonymous Request Allowed":                               "检测允许匿名用户发出的任何请求",
	"Attach/Exec Pod":                                         "检测任何尝试附加/执行到Pod的尝试",
	"EphemeralContainers Created":                             "临时容器创建",
	"Create Disallowed Namespace":                             "检测试图创建的namespace不在已知范围",
	"Pod Created in Kube Namespace":                           "检测在kube-system或者kube-public下创建pod",
	"Service Account Created in Kube Namespace":               "检测在kube-system或者kube-public下创建serviceAccount",
	"System ClusterRole Modified/Deleted":                     "检测对系统clusterRole的修改和删除",
	"Attach to cluster-admin Role":                            "检测附加到集群管理的角色绑定",
	"ClusterRole With Wildcard Created":                       "检测还有通配符的集群角色的创建",
	"ClusterRole With Write Privileges Created":               "检测含有特权的集群角色的创建",
	"ClusterRole With Pod Exec Created":                       "检测任何尝试创建可以执行到Pod的Role / ClusterRole的尝试",
	"K8s Deployment Created":                                  "检测deployment的创建",
	"K8s Deployment Deleted":                                  "检测deployment的删除",
	"K8s Service Created":                                     "检测service的创建",
	"K8s Service Deleted":                                     "检查service的删除",
	"K8s ConfigMap Created":                                   "检查configmap的创建",
	"K8s ConfigMap Deleted":                                   "检查configmap的删除",
	"K8s Namespace Created":                                   "检查namespace的创建",
	"K8s Namespace Deleted":                                   "检查namespace的删除",
	"K8s Serviceaccount Created":                              "检查serviceAccount创建",
	"K8s Serviceaccount Deleted":                              "检查serviceAccount删除",
	"K8s Role/Clusterrole Created":                            "检查role/clusterRole的创建",
	"K8s Role/Clusterrole Deleted":                            "检查role/clusterRole的删除",
	"K8s Role/Clusterrolebinding Created":                     "检查role/clusterrolebinding的创建",
	"K8s Role/Clusterrolebinding Deleted":                     "检查role/clusterrolebinding的删除",
	"K8s Secret Created":                                      "检查secret的创建",
	"K8s Secret Deleted":                                      "检查secret的删除",
	"All K8s Audit Events":                                    "检查所有的k8s审计事件",
	"Full K8s Administrative Access":                          "通过可能是具有完全访问权限的管理员的用户名来检测任何k8s操作。",
	"Ingress Object without TLS Certificate Created":          "检测ingress对象没有配置tls证书",
	"Untrusted Node Successfully Joined the Cluster":          "检查不受信任节点加入集群",
	"Untrusted Node Unsuccessfully Tried to Join the Cluster": "对于不在允许节点列表中的节点，检测到未成功加入集群的尝试。",
}
